<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * https://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\MailMagazine44\Repository;

use Doctrine\Persistence\ManagerRegistry;
use Eccube\Repository\AbstractRepository;
use Plugin\MailMagazine44\Entity\MailMagazineTemplate;

/**
 * MailMagazine.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @extends AbstractRepository<MailMagazineTemplate>
 */
class MailMagazineTemplateRepository extends AbstractRepository
{
    /**
     * MailMagazineTemplateRepository constructor.
     *
     * @param ManagerRegistry $registry
     * @param string $entityClass
     */
    public function __construct(ManagerRegistry $registry, string $entityClass = MailMagazineTemplate::class)
    {
        parent::__construct($registry, $entityClass);
    }

    /**
     * find all.
     *
     * @return list<MailMagazineTemplate>
     */
    public function findAll(): array
    {
        $query = $this
            ->getEntityManager()
            ->createQuery('SELECT m FROM Plugin\MailMagazine44\Entity\MailMagazineTemplate m ORDER BY m.id DESC');
        /** @var list<MailMagazineTemplate> $result */
        $result = $query->getResult();

        return $result;
    }
}
