<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * https://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\MailMagazine44\Tests\Web\Front;

use Eccube\Common\Constant;
use Eccube\Entity\Customer;
use Eccube\Repository\CustomerRepository;
use Eccube\Tests\Web\AbstractWebTestCase;

class MailMagazineEventOnRenderMypageChangeTest extends AbstractWebTestCase
{
    /**
     * @var CustomerRepository
     */
    protected $customerRepository;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->customerRepository = $this->entityManager->getRepository(Customer::class);
    }

    /**
     * @return array<string, mixed>
     */
    protected function createFormData(): array
    {
        $faker = $this->getFaker();
        $tel = explode('-', $faker->phoneNumber);

        $email = $faker->safeEmail;
        $password = $faker->lexify('?????????????').'a1';
        $birth = $faker->dateTimeBetween;

        $form = [
            'name' => [
                'name01' => $faker->lastName,
                'name02' => $faker->firstName,
            ],
            'kana' => [
                'kana01' => 'テスト',
                'kana02' => 'タロウ',
            ],
            'company_name' => $faker->company,
            'postal_code' => '1234567',
            'address' => [
                'pref' => '5',
                'addr01' => $faker->city,
                'addr02' => $faker->streetAddress,
            ],
            'phone_number' => $tel[0].$tel[1].$tel[2],
            'email' => [
                'first' => $email,
                'second' => $email,
            ],
            'plain_password' => [
                'first' => $password,
                'second' => $password,
            ],
            'birth' => [
                'year' => $birth->format('Y'),
                'month' => $birth->format('n'),
                'day' => $birth->format('j'),
            ],
            'sex' => 1,
            'job' => 1,
            '_token' => 'dummy',
        ];

        return $form;
    }

    public function testOnRenderMypageChangeNotLogin(): void
    {
        $this->client->request('GET',
            $this->generateUrl('mypage_change')
        );

        $this->assertFalse($this->client->getResponse()->isSuccessful());
    }

    public function testOnRenderMypageChange(): void
    {
        $Customer = $this->createCustomer();
        $this->loginTo($Customer);

        $crawler = $this->client->request('GET',
            $this->generateUrl('mypage_change')
        );

        $this->assertTrue($this->client->getResponse()->isSuccessful());
        $this->assertEquals(1, $crawler->filter('#entry_mailmaga_flg')->count());
    }

    public function testOnRenderMypageChangePost(): void
    {
        $Customer = $this->createCustomer();
        $this->loginTo($Customer);
        $updateFlg = Constant::ENABLED;
        $form = $this->createFormData();
        $form['mailmaga_flg'] = $updateFlg;

        $this->client->request('POST',
            $this->generateUrl('mypage_change'),
            [
                'entry' => $form,
            ]
        );

        $this->entityManager->clear();
        $Customer = $this->customerRepository->find($Customer->getId());
        $this->actual = $Customer->getMailmagaFlg();
        $this->expected = $updateFlg;
        $this->verify();
    }
}
