<?php
/**
 * Created by PhpStorm.
 * User: lqdung
 * Date: 5/17/2016
 * Time: 9:55 AM
 */

namespace Plugin\MailMagazine\Tests\Repository;


use Plugin\MailMagazine\Tests\Web\MailMagazineCommon;

class MailMagazineSendCustomerRepositoryGetSendCustomerByNotSuccessTest extends MailMagazineCommon
{
    private $Customer;
    private $SendHistory;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->Customer = $this->createMailMagazineCustomer();
        $this->SendHistory = $this->createSendHistoy($this->Customer);
    }

    public function testGetSendCustomerByNotSuccess()
    {
        $result = $this->app['eccube.plugin.mail_magazine.repository.mail_magazine_send_customer']
            ->getSendCustomerByNotSuccess($this->SendHistory->getId());
        $this->actual = $result[0]['send_id'];
        $this->expected = $this->SendHistory->getId();
        $this->verify();
    }
}