<?php
/**
 * This file is part of EC-CUBE
 *
 * Copyright(c) 2000-2015 LOCKON CO.,LTD. All Rights Reserved.
 * http://www.lockon.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\MailMagazine\Tests\Repository;


use Plugin\MailMagazine\Tests\Web\MailMagazineCommon;

class MailMagazineSendCustomerRepositoryGetSendCustomerByNotSuccessTest extends MailMagazineCommon
{
    private $Customer;
    private $SendHistory;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->Customer = $this->createMailMagazineCustomer();
        $this->SendHistory = $this->createSendHistoy($this->Customer);
    }

    public function testGetSendCustomerByNotSuccess()
    {
        $result = $this->app['eccube.plugin.mail_magazine.repository.mail_magazine_send_customer']
            ->getSendCustomerByNotSuccess($this->SendHistory->getId());
        $this->actual = $result[0]['send_id'];
        $this->expected = $this->SendHistory->getId();
        $this->verify();
    }
}