services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Plugin\MailMagazine44\Service\MailMagazineService:
  Plugin\MailMagazine44\Event\MailMagazineHistoryFilePaginationSubscriber:
