services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Plugin\MailMagazine4\Service\MailMagazineService:
  Plugin\MailMagazine4\Event\MailMagazineHistoryFilePaginationSubscriber:
